apiVersion: v1
kind: PersistentVolume
metadata:
  name: internet-speeds-db
  labels:
    app: internet-speeds
    use: db
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /media/internet-speeds/db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: internet-speeds-graphs
  labels:
    app: internet-speeds
    use: output
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /media/internet-speeds/graphs
