apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: internet-speeds-db
  namespace: internet-speeds
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: local
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: internet-speeds
      use: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: internet-speeds-graphs
  namespace: internet-speeds
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: internet-speeds
      use: output
